spring:
  application:
    name: alma-payment

  datasource:
    url: jdbc:postgresql://localhost:5432/alma_payment
    username: postgres
    password: postgres
  jpa:
    hibernate: ddl-auto=validate
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
